events {}

# Define which servers to include in the load balancing scheme.
#https://www.digitalocean.com/community/tutorials/understanding-nginx-server-and-location-block-selection-algorithms-pt

http {
    
   upstream ping {
        server microservice-calcatividade-ping-1:5000;
        server microservice-calcatividade-ping-2:5000;
     }

    upstream calc{
        server microservice-calcatividade-calc-1:5000;
    }

    upstream soma{
        server microservice-calcatividade-soma-1:5000;
    }

    upstream sub{
        server microservice-calcatividade-sub-1:5000;
    }

    upstream mult {
        server microservice-calcatividade-mult-1:5000 weight=3;
        server microservice-calcatividade-mult-2:5000;
        server microservice-calcatividade-mult-3:5000 backup;
    }
# This server accepts all traffic to port 80 and passes it to the upstream.
     server {
         listen 80;
        
         server_name app.com;

         location /ping {
              proxy_pass http://ping;
         }

         location /calc {
              proxy_pass http://calc;
         }

         location /soma {
              proxy_pass http://soma;
         }

         location /sub {
              proxy_pass http://sub;
         }

         location /mult {
              proxy_pass http://mult;
         }
     }
}
